package com.twlkyao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.twlkyao.dao.FileInfo;

import com.twlkyao.dao.FileInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileInfoDaoConfig;

    private final FileInfoDao fileInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileInfoDaoConfig = daoConfigMap.get(FileInfoDao.class).clone();
        fileInfoDaoConfig.initIdentityScope(type);

        fileInfoDao = new FileInfoDao(fileInfoDaoConfig, this);

        registerDao(FileInfo.class, fileInfoDao);
    }
    
    public void clear() {
        fileInfoDaoConfig.getIdentityScope().clear();
    }

    public FileInfoDao getFileInfoDao() {
        return fileInfoDao;
    }

}
